### ISSUE TITLE
Doesn't work with poetry 1.4 (2023-02-27)

### ISSUE THREAD

**Issue by faxm0dem** [spoorn/poeblix#10]
Poeblix fails with newest version of poetry:

```
cannot import name 'Pool' from 'poetry.repositories' (/usr/local/lib/python3.8/site-packages/poetry/repositories/__init__.py)
```

**Comment by spoorn** [comment]
poetry 1.4.0+ now supported in poeblix 0.8+

**Comment by Caetan95** [comment]
Hello, thanks for your work!!

We have a similar problem using poetry 1.2.0

```
Package operations: 1 install, 0 updates, 0 removals
  • Installing poeblix (0.8)
cannot import name 'RepositoryPool' from 'poetry.repositories' (/usr/local/lib/python3.9/site-packages/poetry/repositories/__init__.py)
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

Downgrading it to poeblix 0.7.0 seems to work, but this forces us to set the specific poeblix version. Any clue why it can't find `RepositoryPool` on the latest version?

Thanks!

**Comment by spoorn** [comment]
Poetry had a backwards incompatible change in 1.4.0, so different versions of poeblix is needed for different Poetry versions.  I will add a table to the README soon to show the version mappings
